apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: GEMINI_API_KEY
          value: "dummy"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: grok-secret
              key: api-key
        - name: OPENAI_API_BASE
          value: "https://api.groq.com/openai/v1"
        - name: LLM_PROVIDER
          value: openai
        ports:
        - containerPort: 8080

